### ISSUE TITLE
DaynaPort, Atari: ARP packets not being padded over Wifi 

### ISSUE THREAD

**Issue by akuker** [akuker/RASCSI#619] opened 2022-01-26 02:06 UTC
# Info

- Which version of Pi are you using: Raspberry Pi 2
- Which github revision of software: 21.12
- Which board version: 2.4a
- Which computer is the RaSCSI connected to: Atari ST

# Describe the issue
_(The following was reported by Roger Burrows)_
I have a trace of the data that the driver is seeing.  All ARP packets are
being rejected by the driver because the data length is too short.  To the best
of my knowledge, Ethernet requires a minimum 64-byte length (including CRC);
however, the packets in question are only 46 bytes long including CRC. 
Therefore they are being rejected as illegal length, and the system cannot
determine a MAC address for any IP.  This apparently only happens when using
wireless, since I see no problems on my wired system (ARP packets are being
padded to 64 bytes).

Hope this helps you to find the problem.  Let me know if you need more details.

**Comment by anodynesoftware** [comment] 2022-01-26 22:50
I've investigated further. Checking on Wikipedia, I discovered that WiFi frames, although very similar to Ethernet frames, have NO minimum payload size (please excuse my prior ignorance). This explains why there is a problem with wireless but nor wired networks.  Any frame shorter than 64 bytes must be padded out if you are simulating a wired connection. It looks like it should be a relatively simple fix around line 290 of scsi_daynaport.cpp.

**Comment by uweseimet** [comment] 2022-01-27 10:12
@anodynesoftware Would you be willing to create a feature branch and apply the required change? Unfortunately I currently don't have any working hardware which I could use for testing the Daynaport emulation. But maybe @mzryz or @rdmark can test.

**Comment by mzryz** [comment] 2022-01-28 14:42
Yes I would be very keen to test out any possible fix. Thank you for finding this Roger.

**Comment by rdmark** [comment] 2022-01-28 15:15
As a side note, it is probably worth testing AppleShare DDP file transfers over wifi when using DaynaPort after a fix has been merged. With the current code, such file transfers frequently stall.

**Comment by uweseimet** [comment] 2022-01-29 14:05
@rdmark  @mzryz There is a _fix_issue_619 branch now, with a simple fix as suggested by @anodynesoftware. At least I think this is what he means.
I do not have a good test setup, but I could verify that Netscape Communicator still works with my Mac and a wireless connection, and that the modified code is executed now and then. But this setup was also working before the change, so I cannot tell whether the change makes any difference.

**Comment by mzryz** [comment] 2022-01-29 15:08
Thanks @uweseimet I am away for a day or two will test as soon as I am back. Thank you.

**Comment by anodynesoftware** [comment] 2022-01-30 00:52
On 29 Jan 2022 at 6:06, Uwe Seimet wrote:

> @rdmark  @mzryz There is a _fix_issue_619 branch now, with a simple fix as
> suggested by @anodynesoftware. At least I think this is what he means.
> I do not have a good test setup, but I could verify that Netscape Communicator
> still works with my Mac and a wireless connection, and that the modified code
> is executed now and then. But this setup was also working before the change,
> so I cannot tell whether the change makes any difference.
> 
I'm not sure if this will work, since you don't change the size in buf[], and 
the buffer itself is not expanded.  But I haven't investigated enough about how 
buffers are handled to know if either matters.

If it doesn't work, @mzryz, please provide another trace.

Roger

**Comment by rdmark** [comment] 2022-01-30 01:34
FWIW, I tested the given branch, and did not run into any regressions.
Actually, the test case that previously failed (AppleShare file transfers stalling over wifi with DaynaPort) is working well now. However, it's been months since I last tested it, so there could have been other changes in the meantime which resolved this issue.

**Comment by uweseimet** [comment] 2022-01-30 09:38
@rdmark Can you please check whether your test case is also working with the develop branch? It would be good to know which of the changes in the bugfix branch make a difference, and which do not.

@anodynesoftware The buffer appears to have a static (ugly) size. From scsi_daynaport.h:

```
const int DAYNAPORT_BUFFER_SIZE = 0x1000000;
```

Regarding the size in buf[], I do not know whether rx_packet_size or (rx_packet_size + DAYNAPORT_READ_HEADER_SZ) should be 64 bytes. The latter is returned to the caller, the first is set in the buffer.

**Comment by anodynesoftware** [comment] 2022-01-30 16:41
The data returned by a read on real Dayanaport hardware is as follows:
- 2 bytes bigendian packet length
- 4 bytes flags
- N bytes ethernet packet
- 4 bytes CRC (never used by the driver, assumed to be validated by the hardware)

The value in the first 2 bytes is N+4.

The length used by the driver is taken from the first two bytes of the buffer. The driver checks them for a valid value corresponding to allowed values for N (60 to 1514 inclusive). So the first two bytes of the buffer must be set to a value between 64 & 1518 inclusive.

IIRC, the actual length of data returned is not easily obtained from SCSIDRV, so is not used. This does not matter on real hardware, since the info is contained in the first two bytes of the buffer.

**Comment by uweseimet** [comment] 2022-01-30 18:07
@anodynesoftware I'm assuming you are referring to your driver, but there are also others, in particular for the Mac.

If we were manipulating the size of LLLL, so that it is always at least 64, wouldn't that collide with the checksum CCCCCCCC? The checksum has already been generated when the Read() method is called in scsi_daynaport.cpp, and it has been added to the buffer right after the actual packet:

```
// The CRC was already appended by the ctapdriver
```

It can only have been calculated for the original byte count in LLLL. Changing the value of LLLL in the Read() method would cause issues with the existing checksum if the original size was less than 64. Not only the checksum might be wrong, but also its location in the returned block of data. Your driver might ignore this checksum, but other drivers might not and might fail due to a checksum error. Any thoughts on this?

@rdmark @mzryz I have updated the feature branch with the suggested change for LLLL, and did not find any issues with the limited testing I can do on the Mac.

**Comment by uweseimet** [comment] 2022-01-30 18:17
@anodynesoftware One more question: You say that your driver expects N to be at least 60. I'm not familiar with network frames, but in the Daynaport case, does the frame size really depend on LLLL instead of the number of bytes transferred during DATA IN? In order to satisfy the requirement of a minimum frame size, padding the data at the very end (i.e. behind CCCCCCCC) is what I would expect. The receiver can then simply discard anything it does not need. If padding is done in the middle of the payload (between XXXX... and CCCCCCCC) it causes the issues mentioned in my previous comment.

**Comment by anodynesoftware** [comment] 2022-01-30 19:06
On 30 Jan 2022 at 10:17, Uwe Seimet wrote:

> @anodynesoftware One more question: You say that your driver expects N to be
> at least 60. I'm not familiar with network frames, but in the Daynaport case,
> does the frame size really depend on LLLL instead of the number of bytes
> transferred during DATA IN? In order to satisfy the requirement of a minimum
> frame size, padding the data at the very end (i.e. behind CCCCCCCC) is what I
> would expect.

Your expectation is incorrect.  The Daynaport passes on the network frame 
as-is, with the length/flag fields prepended.  This means that the length value 
in the header must include the entire frame and FCS.  And if you take a look at 
the description of Ethernet frame in Wikipedia, for example, it's quite 
specific that the FCS includes any padding.

 The receiver can then simply discard anything it does not need.
> If padding is done in the middle of the payload (between XXXX... and CCCCCCCC)
> it causes the issues mentioned in my previous comment.
> 

Ethernet *requires* that physical frames are at least 60 bytes + the FCS.  The 
FCS, as you pointed out, comes after the data and is calculated on the entire 
data length including any padding.  If a frame isn't at least that minimum 
size, it's illegal.

The basic issue here is that we have to convert WiFi to Ethernet, and that 
means we can't just pass the data as-is, since WiFi allows packets shorter than 
60 bytes whereas Ethernet doesn't.

Roger

**Comment by anodynesoftware** [comment] 2022-01-30 19:06
On 30 Jan 2022 at 10:07, Uwe Seimet wrote:

> @anodynesoftware I'm assuming you are referring to your driver, but there are
> also others, in particular for the Mac.
> 
> If we were manipulating the size of LLLL, so that it is always at least 64,
> wouldn't that collide with the checksum CCCCCCCC? The checksum has already
> been generated when the Read() method is called in scsi_daynaport.cpp, and it
> has been added to the buffer right after the actual packet:
> 
> ```
> // The CRC was already appended by the ctapdriver
> ```
> 
> It can only have been calculated for the original byte count in LLLL. Changing
> the value of LLLL in the Read() method would cause issues with the existing
> checksum if the original size was less than 64. Not only the checksum might be
> wrong, but also its location in the returned block of data. Your driver might
> ignore this checksum, but other drivers might not and might fail due to a
> checksum error. Any thoughts on this?
> 

If that's a real concern (and I have no idea if the Mac driver checks the FCS), 
then probably the simplest thing is to do any required padding in 
CTapDriver::Rx before the CRC is calculated.  But we don't need to do that for 
initial debugging purposes, i.e. if we're just checking that fixing the length 
fixes the specific problem with the FreeMiNT driver.

Roger

**Comment by uweseimet** [comment] 2022-01-30 19:08
@anodynesoftware I agree with what you say about debugging. Correct me if I am wrong, but the current branch should contain now what we need in order to make this initial test.

**Comment by anodynesoftware** [comment] 2022-01-30 20:01
@uweseimet Yes, it seems to be fine for the initial test. I don't have a wireless setup, so like you I'm relying on @mzryz for testing that part. If it clears things up (or even improves things a little), I assume the next step is a change to ctapdriver and then it can be tested on Atari & Mac with wired & WiFi networks. I can do the wired/Atari part as long as someone can explain how to update the RaSCSI code on a headless Pi.

**Comment by mzryz** [comment] 2022-01-30 20:11
@anodynesoftware @uweseimet am currently reinstalling/recompiling from the '_fix_issue_619' branch and will provide some results shortly. Thank you both.

**Comment by uweseimet** [comment] 2022-01-30 20:12
@anodynesoftware Sounds good!

**Comment by uweseimet** [comment] 2022-01-30 20:41
>This explains why there is a problem with wireless but nor wired networks. Any frame shorter than 64 >bytes must be padded out if you are simulating a wired connection.

@anodynesoftware In the case of your driver, wouldn't it be sufficient if you accepted shorter frames? I guess that's what the Mac drivers are doing, because otherwise there should have been issues with them in the past. All in all it's just the overall payload that counts, and not the number and size of the packages, isn't it?

**Comment by anodynesoftware** [comment] 2022-01-30 22:01
On 30 Jan 2022 at 12:41, Uwe Seimet wrote:

> >This explains why there is a problem with wireless but nor wired networks.
> Any frame shorter than 64 >bytes must be padded out if you are simulating a
> wired connection.
> 
> @anodynesoftware In the case of your driver, wouldn't it be sufficient if you
> accepted shorter frames? I guess that's what the Mac drivers are doing,
> because otherwise there should have been issues with them in the past. All in
> all it's just the overall payload that counts, and not the number and size of
> the packages, isn't it?
> 

I don't think "modify the driver to avoid fixing the firmware" is a desirable 
motto for software development when the source for the firmware is readily 
available.

If I was the maintainer for the FreeMiNT DaynaPort driver, I would rather spend 
time fixing the real bug in RaSCSI rather than providing a workaround to that 
problem in the driver.  And as you pointed out, the Atari drivers are not the 
only drivers that might talk to the RaSCSI Daynaport code; there may be other 
drivers that check for valid Ethernet frame lengths, so it is surely better to 
fix the real problem.

Roger

**Comment by uweseimet** [comment] 2022-01-30 22:26
What I am missing is the piece of information stipulating that the packet size returned by the Daynaport must have at least 64 bytes. I agree with you that if this is guaranteed it must be fixed in RaSCSI, because in this case the Daynaport emulation is incorrect.
Just the fact that the Daynaport has an Ethernet connector and was manufactured (I guess) before there was Wifi would IMO not give a robust guarantee, because the general data format is flexible regarding the packet size. I assume there is something else (maybe even something obvious) that backs your argument?

**Comment by mzryz** [comment] 2022-01-31 00:09
@uweseimet @anodynesoftware I can confirm that this DOES fix Wifi/Daynaport for Atari!! Success! My initial testing has been updating time from NTP server and also pinging www.google.co.uk, no drops packets and good latency <40ms. I can do more testing tomorrow.

**Comment by anodynesoftware** [comment] 2022-01-31 03:52
On 30 Jan 2022 at 16:09, mzryz wrote:

> @uweseimet @anodynesoftware I can confirm that this DOES fix Wifi/Daynaport
> for Atari!! Success! My initial testing has been updating time from NTP server
> and also pinging www.google.co.uk, no drops packets and good latency <40ms. I
> can do more testing tomorrow.
> 
Thanks for the update, glad to hear that things are working now.

Roger

**Comment by anodynesoftware** [comment] 2022-01-31 03:52
On 30 Jan 2022 at 14:26, Uwe Seimet wrote:

> What I am missing is the piece of information stipulating that the packet size
> returned by the Daynaport must have at least 64 bytes. I agree with you that
> if this is guaranteed it must be fixed in RaSCSI, because in this case the
> Daynaport emulation is incorrect.
> Just the fact that the Daynaport has an Ethernet connector and was
> manufactured (I guess) before there was Wifi would IMO not give a robust
> guarantee, because the general data format is flexible regarding the packet
> size. I assume there is something else (maybe even something obvious) that
> backs your argument?
> 

Ethernet frames MUST be at least 60 bytes + the 4-byte FCS.  The Daynaport ONLY 
connects to Ethernet.  Therefore the Daynaport can ONLY send frames at least 64 
bytes in length.

Perhaps I'm the one missing something, but this seems obvious to me.

Roger

**Comment by uweseimet** [comment] 2022-01-31 09:08
@anodynesoftware Your perspective is clear to me, even though I don't agree. If your driver was solely based on what the packet data say it would work out of the box, like the Mac drivers.
One last remark on this from my side: A piece of Atari software (driver) that is using undocumented features may still be compatible with all official versions of TOS, but not with EmuTOS. (I'm quite sure that such software exists.) In my perspective this piece of software has a bug, even though it runs fine with any official TOS. In your argumentation it would be EmuTOS (the firmware in this case) that has a bug.

Anyway, it's good to hear from @mzryz that the error analysis was correct.
@anodynesoftware You asked about how to update the RaSCSI code. I suggest that you clone the RaSCSI repository to your Pi and apply the necessary changes to this cloned repository. With a headless Pi everything you need is ssh access. Note that RaSCSI also compiles on a regular Linux PC, i.e. if you have a Linux PC it may be more convenient to edit on the PC (with a plain old text editor or the Eclipse IDE) and just copy the modified files to the Pi for finally compiling and testing there. I suggest to use a new feature branch for your changes, based on the develop branch.

**Comment by uweseimet** [comment] 2022-01-31 10:34
@rdmark Didn't we add any means to provide an explicit interface name for the Daynaport when launching rascsi, e.g.

```
rascsi -ID 6 -t scdp "eth0"
```

Looks as if explicit interface names are currently only supported by rasctl?

**Comment by mzryz** [comment] 2022-01-31 17:18
@uweseimet Hi Uwe, I noticed the branch was deleted without merging. I wouldn't mind getting the fix on another Atari. What are you planning on doing? Cheers

**Comment by uweseimet** [comment] 2022-01-31 17:28
@mzryz This branch was only meant for testing. It does not correctly calculate checksums, and also breaks other things. I suggest to wait for Roger to update the code with the final solution. Till then you can simply copy the scsi_daynaport.cpp file to your other RaSCSI installation you are using with your other Atari and recompile.

**Comment by rdmark** [comment] 2022-01-31 17:33
> @rdmark Didn't we add any means to provide an explicit interface name list for the Daynaport when launching rascsi, e.g.
> 
> ```
> rascsi -ID 6 -t scdp "eth0"
> ```
> 
> Looks as if explicit interface names are currently only supported by rasctl?

Right, I don't think we ever added network interface options to rascsi proper, only to rasctl. It would be somewhat useful to have it in rascsi too.

> @rdmark Can you please check whether your test case is also working with the develop branch? It would be good to know which of the changes in the bugfix branch make a difference, and which do not.

I went back and tested with the latest develop, and my test cases is passing there too. So it must have been a different change from earlier that made it work. Please disregard my previous comment.

**Comment by uweseimet** [comment] 2022-01-31 17:37
@rdmark I just created PR https://github.com/akuker/RASCSI/pull/635, which adds configurable network interface names to rascsi. Now you can say, for instance:

```
rascsi -ID 6 -t scdp "eth0,eth1,wlan0"
```

**Comment by rdmark** [comment] 2022-01-31 18:26
@anodynesoftware We were planning to cut a RaSCSI software release today. Shall we hold off on the release for a few days in anticipation of your patch?

**Comment by anodynesoftware** [comment] 2022-01-31 20:26
On 31 Jan 2022 at 10:27, Daniel Markstedt wrote:

> @anodynesoftware We were planning to cut a RaSCSI software release today.
> Shall we hold off on the release for a few days in anticipation of your
> patch?
> 
Ah, there is a big misunderstanding here.  I have no plans to do any more work 
on RaSCSI, for three reasons:
 . EmuTOS is my full-time "job"
 . I have zero expertise in C++
 . I have no particular interest in RaSCSI

My contribution was limited to identifying the problem, which I have done.  And 
I've also indicated where I think the fix should go.

Roger

**Comment by anodynesoftware** [comment] 2022-01-31 20:26
On 31 Jan 2022 at 1:08, Uwe Seimet wrote:

> @anodynesoftware Your perspective is clear to me, even though I don't agree.
> If your driver was solely based on what the packet data say it would work out
> of the box, like the Mac drivers.

We're just going to have to agree to disagree about this one.  The Atari driver 
DOES work out of the box with real Daynaport hardware.  It obviously does more 
error checking than the Mac drivers, which IMO is not a bad thing in general.

> One last remark on this from my side: A piece of Atari software (driver) that
> is using undocumented features may still be compatible with all official
> versions of TOS, but not with EmuTOS. (I'm quite sure that such software
> exists.) In my perspective this piece of software has a bug, even though it
> runs fine with any official TOS. In your argumentation it would be EmuTOS (the
> firmware in this case) that has a bug.
> 
As far as EmuTOS is concerned, our motto is "TOS is always right".  So 
undocumented features are always supported as much as possible.  A glance 
through the repo history or the online documentation will show many instances 
where we have changed EmuTOS to fix problems with programs that are using 
undocumented features of TOS.

> Anyway, it's good to hear from @mzryz that the error analysis was correct.

Indeed, this is the most important thing.

> @anodynesoftware You asked about how to update the RaSCSI code. I suggest that
> you clone the RaSCSI repository to your Pi and apply the necessary changes to
> this cloned repository. With a headless Pi everything you need is ssh access.
> Note that RaSCSI also compiles on a regular Linux PC, i.e. if you have a Linux
> PC it may be more convenient to edit on the PC (with a plain old text editor
> or the Eclipse IDE) and just copy the modified files to the Pi for finally
> compiling and testing there. I suggest to use a new feature branch for your
> changes, based on the develop branch.
> 
Thanks for the detailed info!  I was hoping there'd be some kind of image 
somewhere I could just copy to the microSD, but it's not really important as 
I'll be returning my loaned Pi/RaSCSI to Tony Kuker shortly.

Roger

**Comment by uweseimet** [comment] 2022-01-31 21:05
Validating the checksum would be the only reasonable way of error checking ;-). Anyhow, Roger, thank you for spending time on identifying the root cause of the problem.

I don't intend to spend time on code changes which, as already pointed out, from my perspective are the wrong way to go. Nevertheless, I just posted the diffs required to get RaSCSI working with Wifi and your driver to the respective topic of the RaSCSI area of the HDDRIVER forum: https://www.hddriver.net/forum/viewtopic.php?t=243. This is the patch which has successfully been tested by @mzryz.

**Comment by uweseimet** [comment] 2022-01-31 21:11
@rdmark Looks as if there is no need to wait for this ticket before the upcoming release. It would be nice, though, if https://github.com/akuker/RASCSI/pull/635 was part of the release.

**Comment by rdmark** [comment] 2022-02-01 05:56
@anodynesoftware My apologies! Thank you so much for your help troubleshooting this issue.

**Comment by rdmark** [comment] 2022-02-01 05:58
@uweseimet Agreed, this particular issue needs some more work, but the other fix seems good to include in the upcoming release.

> @mzryz This branch was only meant for testing. It does not correctly calculate checksums, and also breaks other things. [...]

Just out of curiosity: What other things does that code change break?

**Comment by uweseimet** [comment] 2022-02-01 09:26
@rdmark The other thing is also related to the checksum, so all in all there are two problems, both resulting in a checksum issue:

1. The checksum is calculated incorrectly
2. The checksum is placed at a wrong location in the packet

**Comment by mzryz** [comment] 2022-02-01 13:07
@anodynesoftware @uweseimet I guess if there is no 'clean' way of solving the problem RaSCSI side, if the checksums can potentially cause issues (after some initial testing I successfully accessed internet websites but for some reason FTP didn't seem to work, I need to test this more) then perhaps the Atari Daynaport driver could potentially be forked into a RaSCSI Dayna driver, and made more forgiving as discussed earlier. If this would make everything a bit 'cleaner' without introducing checksum errors. I don't know. Just thoughts on the issue. Please forgive the fact that I do not know the amount of work entailed in modifying a driver.

**Comment by uweseimet** [comment] 2022-02-01 14:07
@mzryz On the packet level where the Daynaport is involved with the protocol (FTP etc.) does not matter, i.e. whatever you are observing cannot be related to the Daynaport emulation.

**Comment by mzryz** [comment] 2022-02-01 14:37
Okay 👌 no worries

**Comment by anodynesoftware** [comment] 2022-02-01 18:03
On 1 Feb 2022 at 5:07, mzryz wrote:

> @anodynesoftware @uweseimet I guess if there is no 'clean' way of solving the
> problem RaSCSI side, if the checksums can potentially cause issues (after some
> initial testing I successfully accessed internet websites but for some reason
> FTP didn't seem to work, I need to test this more)

If FTP isn't working, please send me a trace as before.  Just because we have 
identified one issue, it doesn't mean there aren't others.  But if you can 
browse a web site I would expect that FTP should work: they are both just 
sending data, and arguably FTP is simpler.

Roger

**Comment by mzryz** [comment] 2022-02-01 20:13
@anodynesoftware Hi Roger. I managed to connect to an FTP server after a few attempts. It didn't seem reliable, firstly giving a connection error, then connecting after a second attempt. I transferred two files which were received very slowly at about 10-20k/s, with inconsistent transfer speed, stopping/starting.
I do not know if this proper behavior, so I have done a trace as suggested and attached below:

[FTP_TRC.zip](https://github.com/akuker/RASCSI/files/7981648/FTP_TRC.zip)

Thank you

**Comment by anodynesoftware** [comment] 2022-02-01 21:23
On 1 Feb 2022 at 12:13, mzryz wrote:

> @anodynesoftware Hi Roger. I managed to connect to an FTP server after a few
> attempts. It didn't seem reliable, firstly giving a connection error, then
> connecting after a second attempt. I transferred two files which were received
> very slowly at about 10-20k/s, with inconsistent transfer speed,
> stopping/starting.

If this is on a vanilla Falcon, that may be reasonable for a data rate.  Data 
rates on a TT are around 30-50kB/sec.  The other issues may be due to 
interference with the floppy drive (which only happens on a Falcon).  I may be 
able to tell something from the trace.

> I do not know if this proper behavior, so I have done a trace as suggested and
> attached below:
> 
> [FTP_TRC.zip](https://github.com/akuker/RASCSI/files/7981648/FTP_TRC.zip)
> 
Thanks, I'll take a look at it tomorrow.

Roger

**Comment by mzryz** [comment] 2022-02-01 21:42
This was on the TT (my falcon hasn't got this RaSCSI patch yet) But when I do get it on the Falcon that is accelerated bus and 060 CPU.

**Comment by anodynesoftware** [comment] 2022-02-01 22:06
On 1 Feb 2022 at 13:42, mzryz wrote:

> This was on the TT (my falcon hasn't got this RaSCSI patch yet) But when I do
> get it on the Falcon that is accelerated bus and 060 CPU.
> 
The accelerated Falcon will probably not make a lot of difference, since IMO 
the main reason that things are slow is because you can only transfer a max of 
1514 bytes per SCSI I/O.  When you combine that with the slow data rate of the 
SCSI chip, the overhead for each SCSI I/O, and the fact that you have to poll 
the device, things are never going to be great.

As far as the TT is concerned, I measured data rates with the following setup:
 . gigabit wired network (cat5e)
 . Quick'n'Easy FTP Server on a Win7 box with gigabit network card
 . standard TT (32MHz 68030) running STiNG with my STinG driver
 . my own FTP client (PFTP) on the TT
The rates were as follows:
 . TT -> Win7: 27kB/sec
 . Win7 -> TT: 50kB/sec
This applied (within margins of error) to both Daynaport hardware and RaSCSI.

In that setup, the network is clearly not the bottleneck, nor the Win7 box.  
There is effectively no interference from anything else on the TT.  So if 
you're running FreeMiNT and a wireless network, it's not surprising if it's 
worse; the only question is how much worse.

Roger

**Comment by uweseimet** [comment] 2022-02-08 16:30
Would be great to have a summary of open issues. In particular the status of these questions is not clear to me:

1. Are there any issues with the current (unpatched) Daynaport code and the Atari *with wired connections*?
2. Does the packet length patch resolve all wireless issues?
3. Are there any ftp-specific issues?
4. Roger, you mentioned that the SCSI Driver reports a bus error. Is this still an open issue, and does it only happen with wireless or also with wired connections?

**Comment by anodynesoftware** [comment] 2022-02-08 17:09
On 8 Feb 2022 at 8:31, Uwe Seimet wrote:

> Would be great to have a summary of open issues. In particular the status of
> these questions is not clear to me:
> 
> 1. Are there any issues with the current (unpatched) Daynaport code and the
> Atari *with wired connections*?
Not as far as I know.

> 2. Does the packet length patch resolve all wireless issues?
That's not clear yet.  There is the bus error issue mentioned below, which may 
or may not be associated with wireless.

> 3. Are there any ftp-specific issues?
Also not clear yet.

> 4. Roger, you mentioned that the SCSI Driver reports a bus error. Is this
> still an open issue, and does it only happen with wireless or also with wired
> connections?
> 
Yes, it's still open.  I don't know if it happens with wired connections; I 
didn't see it, but I didn't look for it specifically.

Roger

**Comment by uweseimet** [comment] 2022-02-08 17:18
@anodynesoftware Thank you for the summary!

**Comment by anodynesoftware** [comment] 2022-02-11 02:03
mzryz ran an enhanced trace for me.  It showed that the buffer that was causing the SCSI DMA bus error was located inside valid TT RAM.  So AFAIK, there shouldn't be any error.  I'm guessing a hardware problem, unless there's some obscure thing going on with page tables that someone else can figure out.

At this point, I think the only problem is that the packet length from WiFi connections can be less than the minimum required by the Ethernet specification (which after all is the only connection supported by a real Daynaport).

**Comment by uweseimet** [comment] 2022-02-11 09:00
In this case I'd like to suggest again to merge the existing fix, even though we know that it breaks the ckecksum calculation. My reasoning: We know that this fix does not break the Daynaport emulation for the Mac, and we know that it definitely improves the situation with the Atari. We also are not aware of drivers for any other platform that might have an issue with this fix.
In case somebody digs out a driver for other platforms than the Mac or Atari *and* if this driver only works without this fix, we can easily revert it. But for know the RaSCSI community would most likely profit from this change.

**Comment by anodynesoftware** [comment] 2022-02-11 15:02
On 11 Feb 2022 at 1:00, Uwe Seimet wrote:

> In this case I'd like to suggest again to merge the existing fix, even though
> we know that it breaks the ckecksum calculation. My reasoning: We know that
> this fix does not break the Daynaport emulation for the Mac, and we know that
> it definitely improves the situation with the Atari. We also are not aware of
> drivers for any other platform that might have an issue with this fix.
> In case somebody digs out a driver for other platforms than the Mac or Atari
> *and* if this driver only works without this fix, we can easily revert it. But
> for know the RaSCSI community would most likely profit from this change.
> 
I agree.

**Comment by uweseimet** [comment] 2022-02-11 15:07
@akuker Can you please comment? In case you agree I will create a PR.

**Comment by akuker** [comment] 2022-02-12 05:19
I agree! Let's merge this puppy!

**Comment by uweseimet** [comment] 2022-02-12 08:56
@akuker OK. Can you please review https://github.com/akuker/RASCSI/pull/662 first? I would like to wait for https://github.com/akuker/RASCSI/pull/662 to be merged before creating a PR for the Atari and the Daynaport.

**Comment by uweseimet** [comment] 2022-02-16 08:25
@mzryz Just as discussed the work-around is now contained in the develop branch.

**Closed** 2022-02-16 08:25 UTC

**Comment by mzryz** [comment] 2022-02-16 11:53
> @mzryz Just as discussed the work-around is now contained in the develop branch.

Thank you @uweseimet and @anodynesoftware for making this fix possible, a great benefit for many Atari users, thank you both :)
